// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'my_experience_json.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'my_experience_json.g.dart';

@freezed
class MyExperienceJson with _$MyExperienceJson {
  const factory MyExperienceJson({
    String? destinationTitle,
    String? destinationName,
    String? dateStart,
    String? countLikes,
    List<String>? images,
  }) = _MyExperienceJson;

  factory MyExperienceJson.fromJson(Map<String, Object?> json) =>
      _$MyExperienceJsonFromJson(json);
}
