// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';
import 'package:travel_booking_tour/common/converter/converter__utils.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'comment_json.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'comment_json.g.dart';

@freezed
class CommentJson with _$CommentJson {
  const factory CommentJson({int? id, CommentAttributes? attributes}) =
      _CommentJson;

  factory CommentJson.fromJson(Map<String, Object?> json) =>
      _$CommentJsonFromJson(json);
}

@freezed
class CommentAttributes with _$CommentAttributes {
  const factory CommentAttributes(
      {String? content,
      @ConvertStringToDateTime() DateTime? createdAt,
      @ConvertStringToDateTime() DateTime? updatedAt,
      @ConvertStringToDateTime() DateTime? publishedAt,
      dynamic user}) = _CommentAttributes;

  factory CommentAttributes.fromJson(Map<String, Object?> json) =>
      _$CommentAttributesFromJson(json);
}
