// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'fee_json.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'fee_json.g.dart';

@freezed
class FeeJson with _$FeeJson {
  const factory FeeJson({
    @JsonKey(name: 'number_of_traveler') String? numberOfTraveler,
    String? fee,
  }) = _FeeJson;

  factory FeeJson.fromJson(Map<String, Object?> json) =>
      _$FeeJsonFromJson(json);
}
