// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'language_json.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'language_json.g.dart';

@freezed
class LanguageJson with _$LanguageJson {
  const factory LanguageJson({
    String? id,
    String? name,
  }) = _LanguageJson;

  factory LanguageJson.fromJson(Map<String, Object?> json) =>
      _$LanguageJsonFromJson(json);
}
