// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'meta_json.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'meta_json.g.dart';

@freezed
class MetaJson with _$MetaJson {
  const factory MetaJson({PaginationJson? pagination}) = _MetaJson;

  factory MetaJson.fromJson(Map<String, Object?> json) =>
      _$MetaJsonFromJson(json);
}

@freezed
class PaginationJson with _$PaginationJson {
  const factory PaginationJson(
      {int? page, int? pageSize, int? pageCount, int? total}) = _PaginationJson;

  factory PaginationJson.fromJson(Map<String, Object?> json) =>
      _$PaginationJsonFromJson(json);
}
