// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';
import 'package:travel_booking_tour/common/converter/converter__utils.dart';
import 'package:travel_booking_tour/features/profile/model/photo_json.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'my_experience_json.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'my_experience_json.g.dart';

@freezed
class MyExperienceJson with _$MyExperienceJson {
  const factory MyExperienceJson(
      {int? id,
      String? name,
      String? location,
      @ConvertStringToDateTime() DateTime? createdAt,
      @ConvertStringToDateTime() DateTime? updatedAt,
      @ConvertStringToDateTime() DateTime? publishedAt,
      bool? isFavorite,
      int? likes,
      List<PhotoJson>? multi}) = _MyExperienceJson;

  factory MyExperienceJson.fromJson(Map<String, Object?> json) =>
      _$MyExperienceJsonFromJson(json);
}
