// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'review_json.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'review_json.g.dart';

@freezed
class ReviewJson with _$ReviewJson {
  const factory ReviewJson(
      {int? id,
      String? ratersName,
      String? ratersImage,
      int? rating,
      String? createdAt,
      String? content}) = _ReviewJson;

  factory ReviewJson.fromJson(Map<String, Object?> json) =>
      _$ReviewJsonFromJson(json);
}
