// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';
import 'package:travel_booking_tour/data/model/schedule_point_json.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'schedule_json.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'schedule_json.g.dart';

@freezed
class ScheduleJson with _$ScheduleJson {
  const factory ScheduleJson(
      {int? id,
      String? name,
      List<SchedulePointJson>? schedules}) = _ScheduleJson;

  factory ScheduleJson.fromJson(Map<String, Object?> json) =>
      _$ScheduleJsonFromJson(json);
}
