// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'time_from_to.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'time_from_to.g.dart';

@freezed
class TimeFromTo with _$TimeFromTo {
  const factory TimeFromTo({
    String? timeFrom,
    String? timeTo,
  }) = _TimeFromTo;

  factory TimeFromTo.fromJson(Map<String, Object?> json) =>
      _$TimeFromToFromJson(json);
}
