// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'tour_provider_json.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'tour_provider_json.g.dart';

@freezed
class TourProviderJson with _$TourProviderJson {
  const factory TourProviderJson({
    int? id,
    String? name,
  }) = _TourProviderJson;

  factory TourProviderJson.fromJson(Map<String, Object?> json) =>
      _$TourProviderJsonFromJson(json);
}
