// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';
import 'package:travel_booking_tour/data/model/schedule_json.dart';
import 'package:travel_booking_tour/data/model/tour_provider_json.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'tour_detail_json.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'tour_detail_json.g.dart';

@freezed
class TourDetailJson with _$TourDetailJson {
  const factory TourDetailJson(
      {int? id,
      int? tourGuideId,
      String? destination,
      List<String>? images,
      double? price,
      double? saleOff,
      int? rating,
      int? reviews,
      int? likes,
      bool? isFavorite,
      TourProviderJson? provider,
      String? duration,
      String? description,
      String? departureDate,
      String? departurePlace,
      List<ScheduleJson>? schedule,
      Map<String, String>? prices}) = _TourDetailJson;

  factory TourDetailJson.fromJson(Map<String, Object?> json) =>
      _$TourDetailJsonFromJson(json);
}
