// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';
import 'package:travel_booking_tour/features/profile/model/photo_json.dart';
// required: associates our `main.dart` with the code generated by Freezed
part 'tour_guide_detail_json.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'tour_guide_detail_json.g.dart';

@freezed
class TourGuideDetailJson with _$TourGuideDetailJson {
  const factory TourGuideDetailJson(
      {int? id, TourGuideDetailAttributes? attributes}) = _TourGuideDetailJson;

  factory TourGuideDetailJson.fromJson(Map<String, Object?> json) =>
      _$TourGuideDetailJsonFromJson(json);
}

@freezed
class TourGuideDetailAttributes with _$TourGuideDetailAttributes {
  const factory TourGuideDetailAttributes(
      {@JsonKey(name: 'Introduction') String? introduction,
      String? city,
      String? language,
      String? createdAt,
      String? updatedAt,
      String? publishedAt,
      String? availabletime,
      dynamic fee,
      dynamic videoIntroduction,
      TourGuideDetailAttributesUser? user}) = _TourGuideDetailAttributes;

  factory TourGuideDetailAttributes.fromJson(Map<String, Object?> json) =>
      _$TourGuideDetailAttributesFromJson(json);
}

@freezed
class TourGuideDetailAttributesUser with _$TourGuideDetailAttributesUser {
  const factory TourGuideDetailAttributesUser(
          {TourGuideDetailAttributesUserData? data}) =
      _TourGuideDetailAttributesUser;

  factory TourGuideDetailAttributesUser.fromJson(Map<String, Object?> json) =>
      _$TourGuideDetailAttributesUserFromJson(json);
}

@freezed
class TourGuideDetailAttributesUserData
    with _$TourGuideDetailAttributesUserData {
  const factory TourGuideDetailAttributesUserData(
          {int? id, TourGuideDetailAttributesUserDataAttributes? attributes}) =
      _TourGuideDetailAttributesUserData;

  factory TourGuideDetailAttributesUserData.fromJson(
          Map<String, Object?> json) =>
      _$TourGuideDetailAttributesUserDataFromJson(json);
}

@freezed
class TourGuideDetailAttributesUserDataAttributes
    with _$TourGuideDetailAttributesUserDataAttributes {
  const factory TourGuideDetailAttributesUserDataAttributes(
          {String? username,
          String? email,
          String? provider,
          String? firstName,
          String? lastName,
          String? country,
          TourGuideDetailAttributesUserDataAttributesAvatar? avatar}) =
      _TourGuideDetailAttributesUserDataAttributes;

  factory TourGuideDetailAttributesUserDataAttributes.fromJson(
          Map<String, Object?> json) =>
      _$TourGuideDetailAttributesUserDataAttributesFromJson(json);
}

@freezed
class TourGuideDetailAttributesUserDataAttributesAvatar
    with _$TourGuideDetailAttributesUserDataAttributesAvatar {
  const factory TourGuideDetailAttributesUserDataAttributesAvatar(
          {TourGuideDetailAttributesUserDataAttributesAvatarData? data}) =
      _TourGuideDetailAttributesUserDataAttributesAvatar;

  factory TourGuideDetailAttributesUserDataAttributesAvatar.fromJson(
          Map<String, Object?> json) =>
      _$TourGuideDetailAttributesUserDataAttributesAvatarFromJson(json);
}

@freezed
class TourGuideDetailAttributesUserDataAttributesAvatarData
    with _$TourGuideDetailAttributesUserDataAttributesAvatarData {
  const factory TourGuideDetailAttributesUserDataAttributesAvatarData(
          {int? id, PhotoJson? attributes}) =
      _TourGuideDetailAttributesUserDataAttributesAvatarData;

  factory TourGuideDetailAttributesUserDataAttributesAvatarData.fromJson(
          Map<String, Object?> json) =>
      _$TourGuideDetailAttributesUserDataAttributesAvatarDataFromJson(json);
}
