// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'user_experiences_json.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'user_experiences_json.g.dart';

@freezed
class UserExperienceJson with _$UserExperienceJson {
  const factory UserExperienceJson(
      {int? id,
      String? name,
      String? location,
      List<String>? multi,
      String? guideName,
      String? guideUrl}) = _UserExperienceJson;

  factory UserExperienceJson.fromJson(Map<String, Object?> json) =>
      _$UserExperienceJsonFromJson(json);
}
