// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'setting_menu_item.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'setting_menu_item.g.dart';

@freezed
class SettingMenuItem with _$SettingMenuItem {
  const factory SettingMenuItem({
    String? leadingIcon,
    String? name,
    String? endIcon,
  }) = _SettingMenuItem;

  factory SettingMenuItem.fromJson(Map<String, Object?> json) =>
      _$SettingMenuItemFromJson(json);
}
