// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'onboarding_json.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'onboarding_json.g.dart';

@freezed
class OnboardingJson with _$OnboardingJson {
  const factory OnboardingJson({
    required String description,
    required String content,
  }) = _OnboardingJson;

  factory OnboardingJson.fromJson(Map<String, Object?> json) =>
      _$OnboardingJsonFromJson(json);
}
