// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'destination_json.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'destination_json.g.dart';

@freezed
class DestinationJson with _$DestinationJson {
  const factory DestinationJson({
    int? id,
    String? url,
    String? name,
  }) = _DestinationJson;

  factory DestinationJson.fromJson(Map<String, Object?> json) =>
      _$DestinationJsonFromJson(json);
}
