// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:travel_booking_tour/common/converter/converter__utils.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'photo_json.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'photo_json.g.dart';

@freezed
class PhotoJson with _$PhotoJson {
  const factory PhotoJson({
    int? id,
    String? token,
    String? uploadUrl,
    String? name,
    String? url,
    bool? selected,
    @ConvertStringToDateTime() DateTime? createdAt,
    @ConvertStringToDateTime() DateTime? publishedAt,
    @ConvertStringToDateTime() DateTime? updatedAt,
  }) = _PhotoJson;

  // To JSON
  const PhotoJson._();

  factory PhotoJson.fromJson(Map<String, Object?> json) =>
      _$PhotoJsonFromJson(json);
}
