// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'user_info.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'user_info.g.dart';

@freezed
class UserInfoJson with _$UserInfoJson {
  const factory UserInfoJson(
      {int? id,
      String? username,
      String? firstName,
      String? lastName,
      String? avatar,
      String? cover,
      String? email,
      String? provider,
      bool? confirmed,
      bool? blocked,
      String? createdAt,
      String? updatedAt,
      String? type}) = _UserInfoJson;

  factory UserInfoJson.fromJson(Map<String, Object?> json) =>
      _$UserInfoJsonFromJson(json);
}
