// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'type_filter_json.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'type_filter_json.g.dart';

@freezed
class TypeFilterJson with _$TypeFilterJson {
  const factory TypeFilterJson({
    String? id,
    String? name,
  }) = _TypeFilterJson;

  factory TypeFilterJson.fromJson(Map<String, Object?> json) =>
      _$TypeFilterJsonFromJson(json);
}
