// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'unsplash_image_json.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'unsplash_image_json.g.dart';

@freezed
class UnSplashResponeJson with _$UnSplashResponeJson {
  const factory UnSplashResponeJson({List<UnSplashResult>? results}) =
      _UnSplashResponeJson;

  factory UnSplashResponeJson.fromJson(Map<String, Object?> json) =>
      _$UnSplashResponeJsonFromJson(json);
}

@freezed
class UnSplashResult with _$UnSplashResult {
  const factory UnSplashResult({UnSplashURL? urls}) = _UnSplashResult;

  factory UnSplashResult.fromJson(Map<String, Object?> json) =>
      _$UnSplashResultFromJson(json);
}

@freezed
class UnSplashURL with _$UnSplashURL {
  const factory UnSplashURL({
    String? raw,
    String? full,
    String? regular,
    String? small,
    String? thumb,
    String? smallS3,
  }) = _UnSplashURL;

  factory UnSplashURL.fromJson(Map<String, Object?> json) =>
      _$UnSplashURLFromJson(json);
}
