// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'schedule_point_json.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'schedule_point_json.g.dart';

@freezed
class SchedulePointJson with _$SchedulePointJson {
  const factory SchedulePointJson({
    int? id,
    String? time,
    String? description,
  }) = _SchedulePointJson;

  factory SchedulePointJson.fromJson(Map<String, Object?> json) =>
      _$SchedulePointJsonFromJson(json);
}
