// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'best_guide_preview_json.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'best_guide_preview_json.g.dart';

@freezed
class BestGuideJson with _$BestGuideJson {
  const factory BestGuideJson({
    String? imageUrl,
    String? name,
    String? address,
    int? ratings,
    int? reviews,
  }) = _BestGuideJson;

  factory BestGuideJson.fromJson(Map<String, Object?> json) =>
      _$BestGuideJsonFromJson(json);
}
