// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'top_experiences_preview_json.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'top_experiences_preview_json.g.dart';

@freezed
class TopExperienceJson with _$TopExperienceJson {
  const factory TopExperienceJson({
    String? guideImageUrl,
    String? destinationImageUrl,
    String? name,
    String? description,
    String? address,
  }) = _TopExperienceJson;

  factory TopExperienceJson.fromJson(Map<String, Object?> json) =>
      _$TopExperienceJsonFromJson(json);
}
