// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'top_journey_preview_json.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'top_journey_preview_json.g.dart';

@freezed
class TopJourneyJson with _$TopJourneyJson {
  const factory TopJourneyJson({
    String? destinationTitle,
    String? imageUrl,
    String? dateStart,
    int? quantities,
    double? price,
    int? ratings,
    int? likes,
  }) = _TopJourneyJson;

  factory TopJourneyJson.fromJson(Map<String, Object?> json) =>
      _$TopJourneyJsonFromJson(json);
}
