// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'travel_news_preview_json.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'travel_news_preview_json.g.dart';

@freezed
class TravelNewJson with _$TravelNewJson {
  const factory TravelNewJson({
    String? destinationImageUrl,
    String? dateStart,
    String? destinationTitle,
  }) = _TravelNewJson;

  factory TravelNewJson.fromJson(Map<String, Object?> json) =>
      _$TravelNewJsonFromJson(json);
}
